# Generated by Django 5.2.6 on 2025-09-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
