# Generated by Django 4.2.5 on 2025-09-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartlist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
